version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: aawni-postgres
    environment:
      POSTGRES_DB: aawni_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aawni-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: aawni-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - aawni-network

  # Next.js Application (for production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aawni-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/aawni_db
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
    depends_on:
      - postgres
      - redis
    networks:
      - aawni-network

  # Adminer for database management (optional)
  adminer:
    image: adminer:latest
    container_name: aawni-adminer
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - aawni-network

volumes:
  postgres_data:
  redis_data:

networks:
  aawni-network:
    driver: bridge